# testsuite configuration for FV3 model

# set model name
model: fv3

# input namelist wildcard
nml_wildcard: '*.nml'

# input dir link name (use . for same as in data dir)
indir_link: 'INPUT'

# name of output directories to create
outdir_name: [RESTART]

# list of input namelists
l_files: [input.nml]

# file containing the parallization options (nproc ...)
par_file: input.nml

# file containing time step information
dt_file: 

# file containing the lasync_io flag
io_file: 

# file containing the test result
res_file: TEST_RES

# file use for the tolerance checker
yufile: output_stat.dat

# list of dual parameters (which may be interchanged in the namelists)
dual_params: []

# which namelist file contains switch to activate testsuite output
nl_ts_switch: 

# where are all namelists echoed after execution
config_nl: "logfile.000000.out"

# is preturbation necessary
pert_avail: True
